### ISSUE TITLE
jqapi.ru website is down

### ISSUE THREAD

**Issue by amalitsky** [futurecolors/jqapi.ru#7]
Now it redirects to airline tickets re-seller/aggregator. Is it gone forever?
Ok, according to [whois](https://www.whois.com/whois/jqapi.ru) domain name is gone. Very sad!
Seems like now someone has to fork and publish somewhere else.

**Comment by coagulant** [comment]
If you would like to take over maintaining the repo, let me know, please.

**Comment by amalitsky** [comment]
For now I've just published it as is on [jqapi.icode.ru](jqapi.icode.ru). This is my pet projects domain (non commercial).
I need to look into source code and reach back to you.
